export default {
  namespaced: true,
  state: {
    sampleText: `CREATE TABLE DEPARTAMENTOS(
  D_ CHAR(2) NOT NULL,
  DNOMBRE CHAR(6) NOT NULL,
  CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY(D_));
  CREATE TABLE CARRERAS(
    C_ CHAR(2) NOT NULL,
    CNOMBRE CHAR(3) NOT NULL,
    VIGENCIA CHAR(4) NOT NULL,
    SEMESTRES NUMERIC(2) NOT NULL,
    D_ CHAR(2) NOT NULL,
    CONSTRAINT PK_CARRERAS PRIMARY KEY(C_),
    CONSTRAINT FK_CARRERAS FOREIGN KEY (D_) REFERENCES DEPARTAMENTOS(D_));
    CREATE TABLE ALUMNOS(
      A_ CHAR(2) NOT NULL,
      ANOMBRE CHAR(20) NOT NULL,
      GENERACION CHAR(4) NOT NULL,
      SEXO CHAR(1) NOT NULL,
      C_ CHAR(2) NOT NULL,
      CONSTRAINT PK_ALUMNOS PRIMARY KEY(A_),
      CONSTRAINT FK_ALUMNOS FOREIGN KEY(C_)REFERENCES CARRERAS(C_));
      CREATE TABLE MATERIAS(
        M_ CHAR(2) NOT NULL,
        MNOMBRE CHAR(6) NOT NULL,
        CREDITOS NUMERIC(2) NOT NULL,
        C_ CHAR(2) NOT NULL,
        CONSTRAINT PK_MATERIAS PRIMARY KEY(M_),
        CONSTRAINT FK_MATERIAS FOREIGN KEY (C_) REFERENCES CARRERAS(C_));
        CREATE TABLE PROFESORES(
          P_ CHAR(2) NOT NULL,
          PNOMBRE CHAR(20) NOT NULL,
          EDAD NUMERIC(2) NOT NULL,
          SEXO CHAR(1)NOT NULL,
          ESP CHAR(4) NOT NULL,
          GRADO CHAR(3) NOT NULL,
          D_ CHAR(2) NOT NULL,
          CONSTRAINT PK_PROFESORES PRIMARY KEY(P_),
          CONSTRAINT FK_PROFESORES FOREIGN KEY (D_) REFERENCES DEPARTAMENTOS(D_));
          CREATE TABLE INSCRITOS(
            R_ CHAR(3) NOT NULL,
            A_ CHAR(2) NOT NULL,
            M_ CHAR(2) NOT NULL,
            P_ CHAR(2) NOT NULL,
            TURNO CHAR(1) NOT NULL,
            SEMESTRE CHAR(6) NOT NULL,
            CALIFICACION NUMERIC(3) NOT NULL,
            CONSTRAINT PK_INSCRITOS PRIMARY KEY(R_),
            CONSTRAINT FK_INSCRITOS_01 FOREIGN KEY (A_) REFERENCES ALUMNOS(A_),
            CONSTRAINT FK_INSCRITOS_02 FOREIGN KEY (M_) REFERENCES MATERIAS(M_),
            CONSTRAINT FK_INSCRITOS_03 FOREIGN KEY (P_) REFERENCES PROFESORES(P_));`,
  },
  mutations: {
    SET_SAMPLE_TEXT(state, payload) {
      state.sampleText = payload;
    },
  },
};
